name: "✨ Pull Request Template"
description: PR 템플릿 - 기능 추가, 버그 수정, 리팩터링 등을 위한 PR을 생성합니다.
title: "[PR] 📌 간단한 제목 작성"
labels: ["pull request", "backend"]
body:
  - type: textarea
    id: summary
    attributes:
      label: "📌 작업 개요"
      description: 어떤 작업을 했는지 한눈에 파악할 수 있도록 요약해주세요.
      placeholder: |
        예) 카카오 로그인 연동 및 JWT 발급 기능 추가
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: "🛠 주요 변경 사항"
      description: 변경된 내용을 간단한 리스트로 정리해주세요.
      placeholder: |
        - UserCommandService: 카카오 토큰 조회 로직 추가
        - JwtProvider: JWT 생성 메서드 구현
    validations:
      required: true

  - type: input
    id: related-issue
    attributes:
      label: "🔗 관련 이슈"
      description: 관련된 이슈 번호가 있다면 연결해주세요 (예: #12)
      placeholder: "#이슈번호"
    validations:
      required: false
완료
  - type: checkboxes
    id: test-checklist
    attributes:
      label: "✅ 테스트 내역"
      description: 아래 체크리스트 중 해당 항목을 확인해주세요.
      options:
        - label: [ ] Swagger 또는 Postman으로 API 테스트 완료
        - label: [ ] DB 저장 / 조회 정상 동작 확인
        - label: [ ] 기존 기능과 충돌 없음 확인
        - label: [ ] 예외 케이스 (에러 응답 등) 테스트 

  - type: textarea
    id: impact
    attributes:
      label: "⚠️ 영향도 및 주의사항"
      description: 다른 기능에 영향을 미치거나 주의가 필요한 사항을 명시해주세요.
      placeholder: |
        - 로그인 응답 포맷 변경 (프론트 반영 필요)
        - 기존 사용자 인증 방식과 충돌 없음
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: "📸 스크린샷 / API 캡처"
      description: UI 변경사항, API 응답 결과 등 시각적으로 확인 가능한 자료가 있다면 첨부해주세요. (drag & drop으로 업로드 가능)
      placeholder: |
        예) Swagger 응답 캡처, Postman 테스트 스크린샷 등
    validations:
      required: false

  - type: textarea
    id: note
    attributes:
      label: "💬 기타 참고 사항"
      description: 코드 리뷰 시 참고하면 좋을 만한 추가 설명을 적어주세요.
      placeholder: 예) TODO: 추후 리팩터링 예정
    validations:
      required: false
