spring:
  port: 8080
  address: 0.0.0.0
  logging:
    level:
      root: info

  kakao:
    client-id: ${Client_ID}
  docker:
    compose:
      enabled: false
  mvc:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  jackson:
    time-zone: Asia/Seoul
  config:
    import: optional:file:.env
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  jwt:
    secret: ${JWT_SECRET}
  data:
    redis:
      #host: redis-container
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket: ${AWS_S3_BUCKET}
