name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]   # 원하는 브랜치명 패턴
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. 레포지토리 코드 체크아웃
        uses: actions/checkout@v4

      - name: 2. JDK 17 세팅
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 3. gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 4. Gradle 빌드 실행 (테스트 제외)
        run: ./gradlew clean build -x test